default:
  language: es
  plugins:
    - advlist
    - autolink
    - link
    - image
    - lists
    - charmap
    - print
    - preview
    - hr
    - anchor
    - pagebreak
    - spellchecker
    - searchreplace
    - wordcount
    - visualblocks
    - visualchars
    - code
    - fullscreen
    - insertdatetime
    - media
    - nonbreaking
    - save
    - table
    - contextmenu
    - directionality
    - emoticons
    - template
    - paste
    - textcolor
  link_list: [{title: 'Vínculo de referencia', value: '#ref'}]
